### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by mcybz** [eugenmihailescu/ebay-purchase-report#20]
No button shows up on the new eBay Purchase historypage.

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/83850054/118860854-db1c9780-b8a9-11eb-93c7-2dd9a637d33b.png">

**Comment by mcybz** [comment]
For anyone else reading this I found awork around is to click on 'Summary' page

https://www.ebay.com/myb/Summary#

And then scroll down to Orders. So it does work! :)

**Comment by slundie** [comment]
Thanks @mcybz  I had the same issue last week and just checked back here and saw your comment, worked like a charm.

**Comment by mcybz** [comment]
> Thanks @mcybz I had the same issue last week and just checked back here and saw your comment, worked like a charm.

Great. Glad it helped someone
