### ISSUE TITLE
Thank you for this tool

### ISSUE THREAD

**Issue by jdesbonnet** [eugenmihailescu/ebay-purchase-report#4]
Hi, this is not a bug report, but a thank you.  It's a *very* useful little utility. I purchase lots of little parts for my workshop from Ebay and keeping track on it all has become a real pain. I feed the JSON output from this into a home grown workshop inventory system (which I plan to release soon). Once again, thanks: it's saved me a lot of re-keying of data.

**Comment by eugenmihailescu** [comment]
Hi Joe, I'm glad it helps you, thanks for sharing that!
