### ISSUE TITLE
csv?

### ISSUE THREAD

**Issue by neslekkim** [eugenmihailescu/ebay-purchase-report#6]
I'm expecting ; or , in csv exports, but they are really tsv exports, tab separated.
Could it be an option to chose field separator value?

**Comment by eugenmihailescu** [comment]
Edit the extension preferences/settings and set the so called "CSV separator" as tab, comma, semicolon.

**Comment by neslekkim** [comment]
Ah!, I didn't find the option dialog first ;), super! 👍
